### ISSUE TITLE
Special chars in password

### ISSUE THREAD

**Issue by thecodekillah** [volkerschulz/D1-Mini-Wi-Fi-RGBW-LED-Controller#1]
My wifi password contains a '&' and this seems not to be working. Changing my password to '123456789' makes the module connect just fine.

**Comment by volkerschulz** [comment]
Fixed in version 1.0.1.

All values **MUST** be url encoded (according to RFC 3986) if containing at least one of the following special chars: "%", "&", "=" or "+" and **SHALL** be url encoded if containing at least one of the reserved characters defined in section 2.2 of RFC 3986.

So "password=hello&world" becomes "password=hello%26world". 

For more information about url encoding pls see https://en.wikipedia.org/wiki/Percent-encoding
